<div class="mfp-hide">
    <div id="festi-cart-pop-up-content" class="order-popup">
        <span class="order-popup__title">Корзина с товаром</span>
        <div class="order-popup-wrapper order-main-wrapper">
            <?php echo $content;?>
            <div class="order-popup__btns">
                <a class="order-popup__btn-resume" href="#" onclick="jQuery.magnificPopup.close()">Продолжить покупки</a>
                <?php if(WC()->cart->get_cart_contents_count() > 0){?>
                    <button class="order-popup__btn-buy" onclick="window.location='/checkout/'">Оформить заказ</button>
                <?php }?>
            </div>
        </div>
    </div>
</div>


<div style="display:none; " class="festi-cart-pop-up-content" id="festi-cart-pop-up-content">
    <span class="festi-cart-closed b-close"><span class="festi-cart-closed-button">&times;</span></span>
    <div class="festi-cart-pop-up-body">
        <div class="festi-cart-pop-up-header">
            <span class="festi-cart-added-to-cart-msg"><?php echo $settings['popupHeaderText'];?></span>
        </div>
        <?php echo $content;?>
        <div class="festi-cart-pop-up-footer">
            <span class="festi-cart-continue b-close"><span class="festi-cart-continue-shopping"><?php echo $settings['popupContinueButtonText'];?></span></span>
        </div>
    </div>
</div>