<div class="festi-cart-pop-up-products-content">
    <?php
    $productsCount = $woocommerce->cart->get_cart_contents_count();

    if ($productsCount > 0) { ?>
        <form method="post" action="/cart/">
            <div class="order-wrapper">
                <ul class="order-list">
                    <?php
                    $changeBgColor = 'festi-cart-next';
                    $maxStep = 5;
                    $step = 0;

                    foreach ($woocommerce->cart->cart_contents as $cart_item_key => $cart_item) {

                        $step++;

                        $changeBgColor = ($changeBgColor != 'festi-cart-next') ? 'festi-cart-next' : '';

                        $product = $cart_item['data'];
                        $productImg = '';
                        if (array_key_exists('displayProductsPictures', $settings)) {

                            if (array_key_exists('productDefaultThumbnail', $settings)) {
                                $img = $product->get_image();
                            } else {
                                if ($settings['productImageMaxHeight'] == 0) {
                                    $settings['productImageMaxHeight'] = $settings['productImageMaxWidth'];
                                }

                                if ($settings['productImageMaxWidth'] == 0) {
                                    $settings['productImageMaxWidth'] = $settings['productImageMaxHeight'];
                                }

                                $productId = ($cart_item['variation_id']) ? $product->id : $product->ID;

                                $variationId = ($cart_item['variation_id']) ? $cart_item['variation_id'] : '';

                                if (!has_post_thumbnail($productId) && !has_post_thumbnail($variationId)) {
                                    $img = $product->get_image();
                                } else {
                                    $img = $product->get_image(array($settings['productImageMaxWidth'], $settings['productImageMaxHeight']));
                                }
                            }

                            $productImg = apply_filters('woocommerce_cart_item_thumbnail', str_replace('class="', 'class="order-item__pic', $img), $cart_item, $cart_item_key);

                            if ($product->is_visible()) {
                                $productImg = '<a class="festi-cart-img" href="' . $product->get_permalink() . '">' . $productImg . '</a>';
                            } elseif ($product->post->post_parent) {
                                $productImg = '<a class="festi-cart-img" href="' . get_permalink($product->post->post_parent) . '">' . $productImg . '</a>';
                            } else {
                                $productImg = '<span class="festi-cart-img">' . $productImg . '</span>';
                            }
                        }

                        $productTitle = '';
                        if (array_key_exists('displayProductTitle', $settings)) {
                            if ($product->is_visible()) {
                                $productTitle = apply_filters('woocommerce_cart_item_name', sprintf('<a class="festi-cart-title" href="%s">%s</a>', $product->get_permalink(), $product->get_name()), $cart_item, $cart_item_key);
                            } elseif ($product->post->post_parent) {
                                $productTitle = apply_filters('woocommerce_cart_item_name', sprintf('<a class="festi-cart-title" href="%s">%s</a>', get_permalink($product->post->post_parent), $product->get_name()), $cart_item, $cart_item_key);
                            } else {
                                $productTitle = apply_filters('woocommerce_cart_item_name', '<span class="festi-cart-title">' . $product->get_name() . '</span>', $cart_item, $cart_item_key);
                            }

                            $productTitle .= '';

                            if (($cart_item['variation_id'])) {
                                $content = $woocommerce->cart->get_item_data($cart_item, true);
                                $content = explode("\n", $content);

                                foreach ($content as $value) {
                                    if (!$value) {
                                        continue;
                                    }
                                    $value_info = explode(":", $value);

                                    if (!empty($value_info[1])) {
                                        $val_2 = rawurldecode($value_info[1]);

                                        $productTitle .= ' <span class="festi-cart-product-variation-attribut">' . $value_info[0] . ' : ' . $val_2 . '</span>';
                                    } else {
                                        $productTitle .= '<span class="festi-cart-product-variation-attribut">' . $value . '</span>';
                                    }
                                }
                            }
                        }
                        ?>

                        <li class="order-item">
                            <div class="order-item__pic-wrapper">
                                <?php echo $productImg; ?>
                            </div>
                            <a class="order-item__title" href=""><?php echo $productTitle; ?></a>

                            <div class="order-item__count-wrapper">
                                <div class="order-item__minus">–</div>
                                <input class="order-item__count-field festi-cart-product-count"
                                       value="<?php echo $cart_item['quantity']; ?>"
                                       name="cart[<?php echo $cart_item_key; ?>][qty]"
                                       data-key="<?php echo $cart_item_key; ?>" pattern="^[ 0-9]+$">

                                <div class="order-item__plus">+</div>
                            </div>
                            <div class="order-item__price"><?php echo woocommerce_price($product->get_price()); ?></div>
                            <a href="<?php echo $cart_item_key; ?>"
                               class="festi-cart-remove-product"><span class="order-item__del">удалить</span></a>
                        </li>
                        <?php
                        if ($step == $settings['dropdownListAmountProducts'] && $settings['dropdownListAmountProducts'] != 0) {
                            break;
                        }
                    } ?>
                </ul>
            </div>
            <div class="order-popup__totals">
                <span class="order-popup__totals-title">Итого:</span>
                <span class="order-popup__totals-sum"><?php echo $woocommerce->cart->get_cart_total(); ?></span>
            </div>
        </form>
    <?php } else { ?>
        <div class="order-empty">
            Здесь пусто...
        </div>
    <?php } ?>
</div>

